### ISSUE TITLE
use of whiskers

### ISSUE THREAD

**Issue by haglo** [nclack/whisk#32]
We want to use your program whiskers.
We have the following problems:

1) When we make a video of the mouse can we trace the whiskers of both sides at the same time?
Can we tape at the same time left side and right side or do we have to tape each side individually?

2) When we tape both sides (right and left) of the mouse in one video and we use the program we get the following error

PS C:\Program Files\WhiskerTracking> trace C:\Users\Olympus\Desktop\Whisk\movies\movie01.mp4 C:\Users\Olympus\Desktop\Whisk\data\movie01.whiskers

Loading...
Done.
Line detector bank loaded from file.------------------------------------------]
Half-space detector bank loaded from file.
C:\Users\clackn\Desktop\src\whisker\src\ffmpeg_adapt.c(236):------------------]
        packet.pts!=0x8000000000000000i64
        Expression evaluated as false.
C:\Users\clackn\Desktop\src\whisker\src\ffmpeg_adapt.c(346):
        ffmpeg_video_next(v,iframe)>=0
        Expression evaluated as false.
C:\Users\clackn\Desktop\src\whisker\src\video.c(253):
        im=get_[k](self->fp,iframe)
        Expression evaluated as false.
C:\Users\clackn\Desktop\src\whisker\src\whisk.c(59):
        im=video_get(v,index,1)
        Expression evaluated as false.
C:\Users\clackn\Desktop\src\whisker\src\whisk.c(168):
        image=load(movie,i,((void _)0))
        Expression evaluated as false.
*_\* ERROR: Could not read frame 301 from C:\Users\Olympus\Desktop\Whisk\movies\movie01.mp4

PS C:\Program Files\WhiskerTracking>

Attention: Our video has 601 frames and the error occurs at frame 300.

**Comment by nclack** [comment]
It should be possible to analyze video with both the left and the right whisker fields in the frame.

The error happens because of an inconsistency in how frame rate is encoded in the mp4.  It might be possible to fix by using [ffprobe](https://ffmpeg.org/ffprobe.html) and [ffmpeg](https://ffmpeg.org/ffmpeg.html) to identify the problem and re-encode the movie.
