### ISSUE TITLE
Missing MacOSX Install Package

### ISSUE THREAD

**Issue by syncrostone** [nclack/whisk#39]
http://openwiki.janelia.org/wiki/display/MyersLab/Whisker+Tracking+Downloads

The full package for Mac OSX, whisk-1.1.0d-Darwin.tar.gz, has been moved or removed from dropbox, leading to this page: https://dl.dropboxusercontent.com/u/782372/Software/whisk-1.1.0d-Darwin.tar.gz when the download link is clicked.

**Comment by nclack** [comment]
Does this link work?

https://www.dropbox.com/s/l65cpmzmic11e7m/whisk-1.1.0d-Darwin.tar.gz

It looks like dropbox changed how the shared links work.  I'll have to contact someone about changing the wiki...

**Comment by syncrostone** [comment]
Yes, that link works -- thank you!
