### ISSUE TITLE
Automatic tracing in fast moving whiskers at a high frame rate

### ISSUE THREAD

**Issue by Krithiga11** [nclack/whisk#42]
@nclack Hi Nathan,
The whisker is not tracked automatically. Have to keep clicking on the whisker to fix the trace line after each frame. 

Thank you,
Krithiga.

**Comment by tvajtay** [comment]
Please use the discord channel/chat.

**Comment by nclack** [comment]
@Krithiga11 

I set up a [chat room](https://discord.gg/Y7QJerr) so that users can help each other out.  Check it out!

Hope that helps.
