### ISSUE TITLE
Mac precompiled not available and error on compiling:

### ISSUE THREAD

**Issue by ninjasatwork** [nclack/whisk#43]
I looked for the precompiled file of the last version for Mac OS . The link is there but the file is missing from the dropbox.

also, when I download the source and try to compile it with cmake, this is the message I get.

-- Found unsuitable Qt version "5.6.2" from /Users/gbmello/anaconda3/bin/qmake
searching /Applications/MATLAB_R2016b.app
Searching /Applications/MATLAB_R2016b.app ... /Applications/MATLAB_R2016b.app/bin/glnxa64
Searching /Applications/MATLAB_R2016b.app ... /Applications/MATLAB_R2016b.app/bin/maci64
searching /Applications/MATLAB_R2016b.app
Searching /Applications/MATLAB_R2016b.app ... /Applications/MATLAB_R2016b.app/bin/glnxa64
Searching /Applications/MATLAB_R2016b.app ... /Applications/MATLAB_R2016b.app/bin/maci64
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
OGG_LIBRARY (ADVANCED)
    linked by target "vsplit" in directory /Users/gbmello/Dropbox/CODE/whiskDarwin
    linked by target "totif" in directory /Users/gbmello/Dropbox/CODE/whiskDarwin
    linked by target "seedtest" in directory /Users/gbmello/Dropbox/CODE/whiskDarwin
    linked by target "preprocess" in directory /Users/gbmello/Dropbox/CODE/whiskDarwin
    linked by target "trace" in directory /Users/gbmello/Dropbox/CODE/whiskDarwin
    linked by target "stripetest" in directory /Users/gbmello/Dropbox/CODE/whiskDarwin
    linked by target "whiskio" in directory /Users/gbmello/Dropbox/CODE/whiskDarwin
    linked by target "whisk" in directory /Users/gbmello/Dropbox/CODE/whiskDarwin

-- Configuring incomplete, errors occurred!

Please could you guide me through a workaround? 
Mac 10.12.6
Xcode
cmake, gawk and bison installed with homebrew.

thanks.

G.

**Comment by nclack** [comment]
Here's the [download link](https://www.dropbox.com/s/l65cpmzmic11e7m/whisk-1.1.0d-Darwin.tar.gz?dl=1).

**Comment by nclack** [comment]
I case you do want to build things one day:

Qt is required for the user interface.  It's finding version 5.6.2 but it requires 4.7 (see the [CmakeLists.txt file](https://github.com/nclack/whisk/blob/d938b9d8dc332d0494cbced6ae844c0ff8250b46/CMakeLists.txt#L322))

**Comment by nclack** [comment]
I also set up a [chat room](https://discord.gg/Y7QJerr) where folks can get connected and ask each other questions.

**Comment by ninjasatwork** [comment]
thank you I appreciate the help.

2018-02-21 18:06 GMT+01:00 Nathan Clack <notifications@github.com>:
