### ISSUE TITLE
Extract measurement data with python

### ISSUE THREAD

**Issue by gmorenomello** [nclack/whisk#44]
Could you please describe the data format so I can pickle out the data in python? or if you have already a function that does it, could you please point me out how to do it?

Thanks

G.

**Comment by nclack** [comment]
In [traj.py](https://github.com/nclack/whisk/blob/master/python/traj.py) there is a python class for reading the measurements table.

I believe that file is in the `share\whisk\python\` in the binary distribution.  The python code depends on the a shared library build from the c code.  That should also already be in `share\whisk\python\`.

If you're interested in digging into the details, you'll have to look at the c source code starting with [measurements-io.c](https://github.com/nclack/whisk/blob/master/src/measurements_io.c).  The file's format evolved over time so you'll see 'v1', 'v2', etc... It looks like [v3](https://github.com/nclack/whisk/blob/master/src/measurements_io_v3.c) is probably the one that's currently written by default.
