### ISSUE TITLE
is it possible to convert ui2 for python3?

### ISSUE THREAD

**Issue by arashfassihi** [nclack/whisk#49]

**Comment by nclack** [comment]
I recommend using the whiski user interface.  

The python interface is too hard for me to maintain.  You could ask around in the [discord ](https://discord.gg/Y7QJerr) to see if someone has a good setup (e.g. Docker) for the python stuff.

Also, if you think it would be valuable please feel free to update the python stuff to python3 yourself and submit a pull request!
